### ISSUE TITLE
Hash hash close button warning message windows 11 andoir 23

### ISSUE THREAD

**Issue by jackdevey** [russellbanks/HashHash#14]
Dear Russell banks 

Is this even the real Russell banks ?

I'm hashing and I sometimes close

Please add close questions

It makes me sad when hashing close

Sweet dreams xx ❤️

William devey

**Comment by russellbanks** [comment]
Hi Jack,

I think what I'm getting from this is that you would like a dialog that would ask if you're sure that you would like to close if you are in the progress of hashing.

In the context menu of file, I should be able to add the logic to do this. However, I don't think I will be able to do this for the window itself as this is managed by Aurora.

Therefore, I can add the logic and dialog in the close application button of the file context menu or just leave it out as this wouldn't be uniform if I am unable to access the logic for the window. An issue could be made with Aurora to allow access the logic of the window. This could already be linked to [#23](https://github.com/kirill-grouchnikov/aurora/issues/23) on Aurora.

**Comment by jackdevey** [comment]
Slacker

**Comment by kirill-grouchnikov** [comment]
Not sure how this relates to that Aurora issue which is about two things:

* Allow creating windows with no title pane at all
* Allow extending the window content into the title pane area

Here it sounds like you want to be able to add some logic block to be run by Aurora when the user clicks the window close button to prevent that window from being closed (say, there's unsaved content, and you want to warn the user about that). If so, that would be a separate Aurora feature request.

**Comment by russellbanks** [comment]
Thanks for the response @kirill-grouchnikov, sorry if I misunderstood the issue on Aurora - I referenced it as a means of saying how the windowing logic will be changing in the future and this could be linked in with this. But yes, a logic block to be run by Aurora when the user clicks the window close button would be ideal for this use case. I've seen that you will be incorporating this into the 1.3 release, so thank you.

**Comment by kirill-grouchnikov** [comment]
In Aurora, I'd only be able to do that for windows decorated by Aurora. If the window is decorated by the OS, Aurora wouldn't be able to intercept any interaction with the native window buttons.
