### ISSUE TITLE
With no file selected, the Calculate button can still be pressed

### ISSUE THREAD

**Issue by jackdevey** [russellbanks/HashHash#18]
Dear Russell Banks,

Unfortunately, when you have lately opened this program & thus have no file chosen, the `Calculate` button still registers press events.

Convention would be to:
*  Disable the button until all required inputs are given and therefore the hash is ready to be calculated, or 
*  Produce a suitable error message explaining the user's blunder, requesting they provide a file

Please find a detailed example below:

![untitled](https://user-images.githubusercontent.com/38474124/168176043-89bafce0-e0fd-4330-a2ea-cc7f47d7c2b5.png)

As is distinctly visible, no file has been opened & the button click event has been called, wrongly causing Windows to set forth an alternate loading cursor.

Whilst I am obviously aware of the minute complexity of this bug compared to your assumed over decorated schedule, it is nevertheless, naturally, something I would greatly appreciate seeing patched in an upcoming release. 

Thank you for taking the time to read & address this issue, I wish you the best of luck in the future!

Yours Sincerely, 

Mr. Jack William Devey

**Comment by russellbanks** [comment]
Thank you for highlighting this to me!

I hadn't considered doing it this way previously. Currently, as you have shown, you can still press the button but nothing will happen. However, it would make more sense in UI design to disable the button rather than make it so that nothing happens if you press it.

**Comment by jackdevey** [comment]
Hindsight is a wonderful thing my friend!
